package com.trabalho.interfaces;

import java.awt.Color;
import java.awt.Dimension;

public class InserirRegistro extends javax.swing.JFrame {

    /**
     * Creates new form InserirRegistro
     */
    public InserirRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        labelInstruction = new javax.swing.JLabel();
        buttonCinema = new javax.swing.JButton();
        buttonEndereco = new javax.swing.JButton();
        buttonFilme = new javax.swing.JButton();
        buttonSessao = new javax.swing.JButton();
        buttonVenda = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JToggleButton();
        buttonCliente = new javax.swing.JButton();  // Novo botão para "Inserir Cliente"

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(51, 51, 51));

        labelTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("INSERIR REGISTRO");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(labelTitle)
                .addGap(179, 179, 179))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(labelTitle)
                .addGap(21, 21, 21))
        );

        panelContent.setBackground(new java.awt.Color(245, 245, 245));  // Cor de fundo suave

        labelInstruction.setBackground(new java.awt.Color(255, 255, 255));
        labelInstruction.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelInstruction.setForeground(new java.awt.Color(51, 51, 51));

        // Botões com a cor azul e texto branco, com tamanhos consistentes
        buttonCinema.setText("CINEMA");
        buttonCinema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // Fonte do botão
        buttonCinema.setBackground(new java.awt.Color(72, 133, 237));  // Cor azul
        buttonCinema.setForeground(Color.WHITE);  // Texto branco
        buttonCinema.setFocusPainted(false);
        buttonCinema.setPreferredSize(new java.awt.Dimension(150, 40));  // Tamanho consistente
        buttonCinema.setMaximumSize(new Dimension(150, 40)); // Forçando tamanho máximo
        buttonCinema.setMinimumSize(new Dimension(150, 40)); // Forçando tamanho mínimo

        buttonEndereco.setText("ENDEREÇO");
        buttonEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); 
        buttonEndereco.setBackground(new java.awt.Color(72, 133, 237));  
        buttonEndereco.setForeground(Color.WHITE);  
        buttonEndereco.setFocusPainted(false);
        buttonEndereco.setPreferredSize(new java.awt.Dimension(150, 40));  // Tamanho consistente
        buttonEndereco.setMaximumSize(new Dimension(150, 40)); 
        buttonEndereco.setMinimumSize(new Dimension(150, 40)); 

        buttonFilme.setText("FILME");
        buttonFilme.setFont(new java.awt.Font("Segoe UI", 0, 14)); 
        buttonFilme.setBackground(new java.awt.Color(72, 133, 237));  
        buttonFilme.setForeground(Color.WHITE);  
        buttonFilme.setFocusPainted(false);
        buttonFilme.setPreferredSize(new java.awt.Dimension(150, 40));  // Tamanho consistente
        buttonFilme.setMaximumSize(new Dimension(150, 40)); 
        buttonFilme.setMinimumSize(new Dimension(150, 40)); 

        buttonSessao.setText("SESSÃO");
        buttonSessao.setFont(new java.awt.Font("Segoe UI", 0, 14)); 
        buttonSessao.setBackground(new java.awt.Color(72, 133, 237));  
        buttonSessao.setForeground(Color.WHITE);  
        buttonSessao.setFocusPainted(false);
        buttonSessao.setPreferredSize(new java.awt.Dimension(150, 40));  // Tamanho consistente
        buttonSessao.setMaximumSize(new Dimension(150, 40)); 
        buttonSessao.setMinimumSize(new Dimension(150, 40)); 

        buttonVenda.setText("VENDA");
        buttonVenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); 
        buttonVenda.setBackground(new java.awt.Color(72, 133, 237));  
        buttonVenda.setForeground(Color.WHITE);  
        buttonVenda.setFocusPainted(false);
        buttonVenda.setPreferredSize(new java.awt.Dimension(150, 40));  // Tamanho consistente
        buttonVenda.setMaximumSize(new Dimension(150, 40)); 
        buttonVenda.setMinimumSize(new Dimension(150, 40)); 

        // Novo botão para "Inserir Cliente"
        buttonCliente.setText("CLIENTE");
        buttonCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); 
        buttonCliente.setBackground(new java.awt.Color(72, 133, 237));  
        buttonCliente.setForeground(Color.WHITE);  
        buttonCliente.setFocusPainted(false);
        buttonCliente.setPreferredSize(new java.awt.Dimension(150, 40));  // Tamanho consistente
        buttonCliente.setMaximumSize(new Dimension(150, 40)); // Forçando tamanho máximo
        buttonCliente.setMinimumSize(new Dimension(150, 40)); // Forçando tamanho mínimo
        buttonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClienteActionPerformed(evt);
            }
        });

        buttonVoltar.setText("VOLTAR");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(labelInstruction)
                        .addGap(82, 82, 82)
                        .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(buttonFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCinema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSessao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonVoltar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonVoltar)
                        .addGap(142, 142, 142)
                        .addComponent(labelInstruction))
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(buttonCinema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSessao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCliente)))  // Novo botão CLIENTE
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void buttonSessaoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO: Adicionar lógica para Sessão
    }                                           

    private void buttonVendaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO: Adicionar lógica para Venda
    }                                           

    private void buttonEnderecoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO: Adicionar lógica para Endereço
    }                                             

    private void buttonCinemaActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO: Adicionar lógica para Cinema
    }                                            

    private void buttonFilmeActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // Navegar para a tela de Inserir Filme
        this.dispose();
        InserirFilme inserirFilme = new InserirFilme();
        inserirFilme.setVisible(true);
    }                                           

    private void buttonClienteActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // Lógica para "Inserir Cliente"
    }                                             

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // Voltar para o Menu Principal
        this.dispose();
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
    }                                            

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonCinema;
    private javax.swing.JButton buttonEndereco;
    private javax.swing.JButton buttonFilme;
    private javax.swing.JButton buttonSessao;
    private javax.swing.JButton buttonVenda;
    private javax.swing.JButton buttonCliente;  // Novo botão de Cliente
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelInstruction;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelContent;
    private javax.swing.JToggleButton buttonVoltar;
    // End of variables declaration                   

}
