/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.trabalho.interfaces;

/**
 *
 * @author samuel
 */
public class InserirRegistro extends javax.swing.JFrame {

    /**
     * Creates new form InserirRegistro
     */
    public InserirRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        painelSuperior = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        painelInferior = new javax.swing.JPanel();
        descricaoLabel = new javax.swing.JLabel();
        botaoCinema = new javax.swing.JButton();
        botaoEndereco = new javax.swing.JButton();
        botaoFilme = new javax.swing.JButton();
        botaoSessao = new javax.swing.JButton();
        botaoVenda = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JToggleButton();
        botaoCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelSuperior.setBackground(new java.awt.Color(51, 51, 51));

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("INSERIR REGISTRO");

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSuperiorLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(179, 179, 179))
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSuperiorLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(21, 21, 21))
        );

        painelInferior.setBackground(new java.awt.Color(255, 255, 255));

        descricaoLabel.setBackground(new java.awt.Color(255, 255, 255));
        descricaoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descricaoLabel.setForeground(new java.awt.Color(255, 255, 255));

        botaoCinema.setBackground(new java.awt.Color(0, 153, 255));
        botaoCinema.setText("CINEMA");
        botaoCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCinemaActionPerformed(evt);
            }
        });

        botaoEndereco.setBackground(new java.awt.Color(0, 153, 255));
        botaoEndereco.setText("ENDEREÇO");
        botaoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnderecoActionPerformed(evt);
            }
        });

        botaoFilme.setBackground(new java.awt.Color(0, 153, 255));
        botaoFilme.setText("FILME");
        botaoFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFilmeActionPerformed(evt);
            }
        });

        botaoSessao.setBackground(new java.awt.Color(0, 153, 255));
        botaoSessao.setText("SESSÃO");
        botaoSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSessaoActionPerformed(evt);
            }
        });

        botaoVenda.setBackground(new java.awt.Color(0, 153, 255));
        botaoVenda.setText("VENDA");
        botaoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVendaActionPerformed(evt);
            }
        });

        botaoVoltar.setText("VOLTAR");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoCliente.setBackground(new java.awt.Color(0, 153, 255));
        botaoCliente.setText("CLIENTE");
        botaoCliente.setActionCommand("CLIENTE");
        botaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelInferiorLayout = new javax.swing.GroupLayout(painelInferior);
        painelInferior.setLayout(painelInferiorLayout);
        painelInferiorLayout.setHorizontalGroup(
            painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInferiorLayout.createSequentialGroup()
                .addGroup(painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInferiorLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(descricaoLabel))
                    .addGroup(painelInferiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoVoltar)))
                .addGap(82, 82, 82)
                .addGroup(painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botaoEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(botaoFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSessao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoCinema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(botaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        painelInferiorLayout.setVerticalGroup(
            painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInferiorLayout.createSequentialGroup()
                .addGroup(painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInferiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descricaoLabel))
                    .addGroup(painelInferiorLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(botaoCinema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSessao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCliente)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void botaoSessaoActionPerformed(java.awt.event.ActionEvent evt) {  
        this.dispose();                                       
        // TODO add your handling code here:
        InserirSessao inserirSessao = new InserirSessao();
        inserirSessao.setVisible(true);
    }                                        

    private void botaoVendaActionPerformed(java.awt.event.ActionEvent evt) {  
        this.dispose();                                       
        // TODO add your handling code here:
        InserirVenda inserirVenda = new InserirVenda();
        inserirVenda.setVisible(true);

    }                                        

    private void botaoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {  
        this.dispose();                                       
        // TODO add your handling code here:
        InserirEndereco inserirEndereco = new InserirEndereco();
        inserirEndereco.setVisible(true);
    }                                        

    private void botaoCinemaActionPerformed(java.awt.event.ActionEvent evt) {   
        this.dispose();                                      
        // TODO add your handling code here:
        InserirCinema inserirCinema = new InserirCinema();
        inserirCinema.setVisible(true);
    }                                        

    private void botaoFilmeActionPerformed(java.awt.event.ActionEvent evt) {  
        this.dispose();                                       
        // TODO add your handling code here:
        InserirFilme inserirFilme = new InserirFilme();
        inserirFilme.setVisible(true);
    }                                        

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        this.dispose();
    
        // Criar e exibir o MenuPrincipal
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        
    }                                              

    private void botaoClienteActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();                                         
        // TODO add your handling code here:
        InserirCliente inserirCliente = new InserirCliente();
        inserirCliente.setVisible(true);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botaoCinema;
    private javax.swing.JButton botaoEndereco;
    private javax.swing.JButton botaoFilme;
    private javax.swing.JButton botaoSessao;
    private javax.swing.JButton botaoVenda;
    private javax.swing.JButton botaoCliente;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JPanel painelInferior;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JToggleButton botaoVoltar;
    // End of variables declaration                   
}
