version: '3.4'

services:
  trabalhocinemamongodb:
    image: trabalhocinemamongodb
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
